# simulation_project/config.yaml
simulation_params:
  kappa: 0.1
  num_trajectories_main: 2500 # Used per individual seed run
  
  # --- Parameters for original Plot 1-4 regimes ---
  num_seed_runs_plot4: 100  # Max seeds to run, primarily for +P stats & Plot 4 +P.
  num_seed_runs_plot4_tw: 3 # Number of seeds for TW for Plot 4 (e.g., 3).
                            # TW will use the first 3 seeds from global_seeds_plot4.
  global_seeds_plot4: [
    42, 123, 789, 734, 890, 567, 37, 236, 106, 888,
    1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
    2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
    3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010,
    4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4009, 4010,
    5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010,
    6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010,
    7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010,
    8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009, 8010,
    9001, 9002, 9003, 9004, 9005, 9006, 9007, 9008, 9009, 9010
  ] # List of 100 seeds.
  
  regime_physical_t_end: # For original Low, Medium, High plots
    Low: 30.0
    Medium: 15.0
    High: 15.0

  # --- Parameters for the N-Scan for Max Squeezing Plot ---
  n_scan_active: true # Set to true to run the n-scan simulations
  n_scan_values: [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
  # MODIFIED: n_scan_seeds to have 50 seeds
  n_scan_seeds: [
    2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
    2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
    2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030,
    2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040,
    2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050
  ] # 50 distinct seeds for n-scan
  n_scan_t_ends: # Physical end times for each n_scan_value
    1: 30.0
    5: 25.0 # Added entry for n=5, adjust time as needed
    10: 20.0
    15: 20.0
    20: 15.0
    25: 15.0 # Added entry for n=25, adjust time as needed
    30: 15.0
    35: 15.0
    40: 15.0
    45: 15.0
    50: 15.0
    55: 15.0
    60: 15.0
    65: 15.0
    70: 15.0
    75: 15.0
    80: 15.0
    85: 15.0
    90: 15.0
    95: 15.0
    100: 15.0
  # --- End of N-Scan Parameters ---

  num_simulation_points: 501 # Global for all simulations (TW and +P)
  num_workers_pplus: null # null for multiprocessing.cpu_count(), or set a specific number

photon_regimes: # For original Plot 1-4
  Low: 1
  Medium: 20
  High: 100

data_handling:
  data_dir: "simulation_data_combined"
  force_rerun_all: false # Set to true to force all simulations to rerun

plotting:
  plot_dir: "plots"
  generate_plot1_squeezing: false
  generate_plot2_pump_depletion: false
  generate_plot3_photon_tracker: false
  generate_plot4_seed_variance: false
  generate_plot_max_squeezing_vs_n: true # Flag for the new plot

  plot_style: 'seaborn-v0_8-whitegrid'
  epsilon_db: 1.0e-15
  vacuum_noise_quad_variance: 0.25
  medium_regime_key_for_plot3: "Medium"
  
  plot_ylim_pump_depletion_default: [0, 120]
  plot_ylim_photon_tracker_default: [-1, 25]
  plot_xlim_physical: [0, 10.0]  # Default physical xlim for plots
  plot_ylim_squeezing: [-10, 5]   # Default ylim for squeezing plots

  plot1_squeezing_regime_limits:
    Low:
      xlim: [0, 30.0]
      ylim: [-10, 10]
    Medium:
      xlim: [0, 15.0]
      ylim: [-15, 25]
    High:
      xlim: [0, 10.0] 
      ylim: [-25, 30]

  plot2_pump_depletion_regime_ylimits:
    Low:
      ylim: [0, 2.0]
    Medium:
      ylim: [0, 25.0]
    High:
      ylim: [0, 110.0]

  plot3_photon_tracker_ylim: [-2, 30]

  # Threshold for the n-scan plot reliability
  n_scan_reliability_std_threshold_linear: 0.035